import { existsSync, readFileSync, appendFileSync } from "fs";
import { createLLM, extractMessageText } from "../llm.js";
import { askConfirmation } from "../prompts.js";
import { failAndExit, ok, printList, section, style, ui, warn, withProgress } from "../ui.js";

function getLLM() {
  try {
    return createLLM();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    failAndExit(message);
  }
}

const IGNORE_PROMPT = `Generate a .gitignore file content for the project described below.
Rules:
- Include only entries relevant to the description
- Group entries by category with comments (e.g., # Dependencies, # Build output, # Environment)
- Do not include entries already in the existing .gitignore
- Return ONLY the .gitignore entries, no explanation

Project description:
{{description}}

Existing .gitignore content (avoid duplicates):
{{existing}}`;

export async function generateGitignore(description: string): Promise<void> {
  const llm = getLLM();

  if (!description.trim()) {
    failAndExit("Provide a project description. Example: gemit ignore \"node project with .env and dist\"");
  }

  const gitignorePath = ".gitignore";
  let existingContent = "";
  if (existsSync(gitignorePath)) {
    existingContent = readFileSync(gitignorePath, "utf8").trim();
  }

  section("IGNORE");

  const prompt = IGNORE_PROMPT
    .replace("{{description}}", description)
    .replace("{{existing}}", existingContent || "(none)");

  const result = await withProgress("AI is generating .gitignore entries...", () => llm.invoke(prompt));
  const suggestions = extractMessageText(result.content);

  if (!suggestions) {
    failAndExit("Failed to generate .gitignore entries.");
  }

  section("SUGGESTIONS");
  console.log();
  const lines = suggestions.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("#")) {
      console.log(`  ${style(trimmed, ui.gray, ui.italic)}`);
    } else if (trimmed) {
      console.log(`  ${style(trimmed, ui.cyan)}`);
    } else {
      console.log();
    }
  }
  console.log();

  const entryCount = lines.filter((l) => l.trim() && !l.trim().startsWith("#")).length;
  printList("Summary", [
    `${entryCount} entries to add`,
    existingContent ? `Appending to existing .gitignore` : `Creating new .gitignore`,
  ]);
  console.log();

  const confirmed = await askConfirmation(
    `${existingContent ? "Append" : "Write"} these entries to .gitignore? (Y/n): `,
    { defaultYes: true }
  );
  if (!confirmed) {
    console.log(warn("CANCELED", ".gitignore was not modified."));
    return;
  }

  const separator = existingContent ? "\n\n" : "";
  appendFileSync(gitignorePath, `${separator}# Generated by gemit ignore\n${suggestions}\n`, "utf8");
  console.log(ok("SAVED", `.gitignore updated with ${entryCount} new entries.`));
}
